baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'BMS Clubs'
theme = 'ananke'

[params]
    background_color_class = "bg-dark-blue"

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Sports"
    identifier = "menu.sports"
    url        = "/"
    weight     = 2

[[menu.main]]
    name       = "Academics"
    identifier = "menu.academics"
    url        = "/"
    weight     = 3

[[menu.main]]
    name       = "Games and Fun"
    identifier = "menu.gamesandfun"
    url        = "/"
    weight     = 4

[[menu.main]]
    name       = "Other Clubs"
    identifier = "menu.otherclubs"
    url        = "/"
    weight     = 5

[[menu.main]]
    name       = "Achievements"
    identifier = "menu.achievements"
    url        = "/"
    weight     = 6

[[menu.main]]
    name       = "Registration"
    identifier = "menu.registration"
    url        = "/"
    weight     = 7

[[menu.main]]
    name       = "Bibliography"
    identifier = "menu.bibliography"
    url        = "/"
    weight     = 8
