baseURL = "https://example.org/"
languageCode = "en-us"
title = "BMS Clubs and Orginizations"
theme = "hugo-universal-theme"

[menu]

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Clubs"
    identifier = "menu.clubs"
    url        = "/img/template-homepage.png"
    weight     = 2

[[menu.main]]
    name       = "How to Join"
    identifier = "menu.howtojoin"
    url        = "/img/template-homepage.png"
    weight     = 3

[[menu.main]]
    name       = "Achievements"
    identifier = "menu.achievements"
    url        = "/img/template-homepage.png"
    weight     = 4